### ISSUE TITLE
Glavni program, kodiranje znakov

### ISSUE THREAD

**Issue by jaanos** [pustotnk/APPR-2014-15#1]
V glavnem programu (`projekt.r`) kličeš vzorčna programa za naslednji dve fazi. Seveda ni smiselno, da ju sedaj kličeš, tako da ju zaenkrat zakomentiraj - v prihodnjih fazah boš seveda to vrnil (pa morda še kaj dodal).

Pri uvozu podatkov podaj parameter `fileEncoding="Windows-1250"`, da bo podatke pravilno uvozilo. Na koncu datoteke CSV imaš nekaj praznih vrstic, ki jih lahko pobrišeš. Potem lahko z `row.names = 1` dosežeš, da so imena nogometašev tudi imena vrstic. V uvoženi tabeli imaš na koncu en prazen stolpec, ki se ga tudi lahko znebiš. Stolpec `Barcelona.career` bi lahko razbil na dve številski spremenljivki: začetek kariere in konec kariere (pri trenutnih igralcih bo ta seveda `NA`). Iz stolpca `Title` bi lahko naredil urejenostno spremenljivko.

Ne pozabi še na grafe in poročilo.

**Comment by pustotnk** [comment]
Zdravo!
Malo mi še dela problemov, ker še pythona nimam od lani in moram včasih kaj
kr premislit... grafa mi zaenkrat ni hotelo narisati in se opravičujem za
zamudo, se bom res potrudil da bom do srede drugače bom pa na vajah prosil
če mi boste pomagali...
hvala za popravke!
lep pozdrav

Dne 08. december 2014 14.27 je Janoš Vidali notifications@github.com
napisal/-a:

**Comment by jaanos** [comment]
Opažam, da imaš v podatkih tudi znake, ki jih kodna tabela _Windows-1250_ ne zajema (Excel sicer predstavi te znake na nek nestandarden način), zato bo treba podatke predstaviti v kodiranju _UTF-8_. Delno bi sicer problem rešil, če bi podatke uvozil neposredno s spletne strani (in tako dobil vsakič aktualne podatke o številu golov), a ker imaš v datoteki CSV še dodano višino, sem ti pretvoril [podatke](https://gist.github.com/jaanos/1a685b35c24ac8f0f81f) v kodiranje _UTF-8_. Klikni na povezavo, potem zgoraj desno na gumb _Raw_, nato pa shrani datoteko namesto obstoječe (ne odpiraj je v Excelu!). Seveda bo potrebno pri uvozu kodiranje nastaviti na `"UTF-8"`.

Risanje grafov imaš v programu `slike/grafi.r`, a ga nikjer ne kličeš - najbolje bo, če ga kličeš v glavnem programu za uvozom. Pri prvem grafu imaš pod vsakim stolpcem dovolj prostora, tako da lahko odstraniš parameter `las = 2`, da se ti imena izpišejo vodoravno. Pri drugem grafu so imena natlačena in spodaj odrezana, tako da jih zmanjšaj npr. na velikost `0.4`. Svetujem tudi, da izpustiš parameter `paper` pri ukazih `pdf`, saj bodo potem grafi v poročilu izgledali večji.

Če boš imel probleme s posebnimi znaki, si poglej navodila, ki sem jih pravkar objavil na spletni učilnici.

V poročilu imaš seznam, kjer si uporabil kar zvezdice. Tak način se uporablja v markdownu (npr. v datotekah `README.md`, pa tudi v issuejih in drugod na GitHubu), v LaTeXu pa uporabi okolje `itemize` in ukaz `\item` za vsako točko. Seveda v poročilo vključi še grafe.

**Comment by pustotnk** [comment]
Zdravo!
večino teh stvari sem že uredil na faksu, vendar mi jih ( sem opazil šele
sedaj ) ni shranilo na git kljub temu da sem pushal... imam narisan tudi že
zemljevid in poročilo, spremenjene grafe... tako da bom jutri na faksu še
enkrat poizkusil s pushom... sedajle sem pa doma uredil kodiranje.

Hvala in lep pozdrav

Dne 17. januar 2015 21.00 je Janoš Vidali notifications@github.com
napisal/-a:

**Comment by jaanos** [comment]
Če imaš narejen zemljevid, potem lahko ta teden na vajah predstaviš svoj projekt. Ker je edini še prost termin v torek, te prosim, da **do jutri** poskrbiš, da bo na GitHub naložena delujoča različica tvojega programa in poročila.

**Comment by jaanos** [comment]
Sedaj ti program deluje - ne pozabi vključiti še grafov in zemljevida v PDF.

Na zemljevidu poskrbi, da bo čitljiv. Namesto, da zmanjšaš imena toliko, da nobenega ni več mogoče prebrati, raje katerega skrajšaj, npr.

``` R
names(imena.drzav) <- imenadrzav
imena.drzav["Netherlands"] <- "NL"
```

Portugalsko in Čile bi bilo smiselno izpisati navpično. To lahko storiš s parametrom `srt = 90` pri ukazu `text`:

``` R
navpicna <- imena.drzav %in% c("Chile", "Portugal")
text(co[!navpicna,],labels=imena.drzav[!navpicna],pos = 1, cex = 0.4)
text(co[navpicna,],labels=imena.drzav[navpicna],pos = 1, cex = 0.4, srt = 90)
```

Seveda bo treba imena še nekoliko premakniti, da bo lepo izgledalo. Morda tudi ni smiselno, da uporabljaš paramete `pos = 1` - ta ti premakne imena nekoliko nižje od podanih koordinat, kar je uporabno predvsem, ko imaš na dejanskih koordinatah narisane točke in bi rad dodal še imena.

Prosim, da se na spletni učilnici prijaviš za termin predstavitve. Potem bom v repozitorij za predstavitve dodal še tvoj projekt.

**Comment by jaanos** [comment]
Vidim, da si popravil, tako da sem kar dodal povezavo. Če boš še kaj spreminjal, odpri issue na repozitoriju za zagovore.
